### ISSUE TITLE
MSP430g2553 doesn't work

### ISSUE THREAD

**Issue by MarcoAAG** [dlbeer/mspdebug#102]
Hi, Im triying to debug on msp430g2553
![1](https://user-images.githubusercontent.com/55122694/109228041-e66a9600-7786-11eb-8325-419234cd136b.png)
with this command
$sudo mspdebug -U 001:051 RF2500
I got this error
"MSPDebug version 0.22 - debugging tool for MSP430 MCUs
Copyright (C) 2009-2013 Daniel Beer <dlbeer@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

rf2500: failed to open RF2500 device"

**Comment by dlbeer** [comment]
On Thu, Feb 25, 2021 at 02:33:21PM -0800, Marco Aguilar wrote:
> Hi, Im triying to debug on msp430g2553
> ![1](https://user-images.githubusercontent.com/55122694/109228041-e66a9600-7786-11eb-8325-419234cd136b.png)
> with this command
> $sudo mspdebug -U 001:051 RF2500
> I got this error
> "MSPDebug version 0.22 - debugging tool for MSP430 MCUs
> Copyright (C) 2009-2013 Daniel Beer <dlbeer@gmail.com>
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> rf2500: failed to open RF2500 device"

That's not an RF2500 device. You'll need to use the "tilib" driver (and
install libmsp430.so if you don't have it already).

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by MarcoAAG** [comment]
Now i received an error when i try to compile the libmsp430.so
![image](https://user-images.githubusercontent.com/55122694/109238182-b1673f00-7798-11eb-846e-5d454cb768fd.png)

**Comment by dlbeer** [comment]
On Thu, Feb 25, 2021 at 04:39:02PM -0800, Marco Aguilar wrote:
> Now i received an error when i try to compile the libmsp430.so
> ![image](https://user-images.githubusercontent.com/55122694/109238182-b1673f00-7798-11eb-846e-5d454cb768fd.png)

Unfortunately I can't help you with that -- it's TI's library, so you'll
need to ask them for support, unless you can find a suitable precompiled
binary somewhere.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by MarcoAAG** [comment]
thks.. greetings
