### ISSUE TITLE
Won't compile (seen on MacOS but seems universal).

### ISSUE THREAD

**Issue by sorber** [dlbeer/mspdebug#113]
When I try to compile mspdebug from source, I'm getting errors regarding the `rf2500_open` function. It appears that it was updated to take 3 additional arguments, but is still being called with 2 args in `rf2500hidapi.c` on line 203. 

I modified the line like this.
`return rf2500_open(devpath, requested_serial, has_vid_pid, vid, pid);`

That seemed to get things working, and it seems reasonable based on the arg names, but I don't know this code well enough to know if that's the fix you want.

**Comment by dlbeer** [comment]
On Thu, Feb 10, 2022 at 12:03:03PM -0800, Jacob Sorber wrote:
> When I try to compile mspdebug from source, I'm getting errors regarding the `rf2500_open` function. It appears that it was updated to take 3 additional arguments, but is still being called with 2 args in `rf2500hidapi.c` on line 203. 
> 
> I modified the line like this.
> `return rf2500_open(devpath, requested_serial, has_vid_pid, vid, pid);`
> 
> That seemed to get things working, and it seems reasonable based on the arg names, but I don't know this code well enough to know if that's the fix you want.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/dlbeer/mspdebug/issues/113
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>

This is OS/X specific (rf2500hidapi only gets built on OS/X), but your
fix looks correct to me. If you wanted to put together a pull request
after testing, I'll merge it.

-- 
Daniel Beer ***@***.***> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B
