### ISSUE TITLE
how about a release?

### ISSUE THREAD

**Issue by carrotIndustries** [dlbeer/mspdebug#13]
It's been more than one year since the last release of mspdebug. Since it seems like the current msp430 debug stack requires a newer mspdebug, how about a release?

**Comment by dlbeer** [comment]
On Fri, May 13, 2016 at 11:23:44AM -0700, Lukas K. wrote:
> It's been more than one year since the last release of mspdebug. Since
> it seems like the current msp430 debug stack requires a newer
> mspdebug, how about a release?

Fair enough -- done (tag v0.24).

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by carrotIndustries** [comment]
Thank you :)
