### ISSUE TITLE
regs problem with MSP430F233

### ISSUE THREAD

**Issue by iddq** [dlbeer/mspdebug#94]
> JTAG ID: 0x89
> Chip ID data:
>   ver_id:         49f2
>   ver_sub_id:     0000
>   revision:       04
>   fab:            60
>   self:           0000
>   config:         00
>   fuses:          87
> Device: MSP430F233
> 
> (mspdebug) regs
>     ( PC: 001fe)  ( R4: 001fe)  ( R8: 001fe)  (R12: 001fe)
>     ( SP: 001fe)  ( R5: 001fe)  ( R9: 001fe)  (R13: 001fe)
>     ( SR: 001fe)  ( R6: 001fe)  (R10: 001fe)  (R14: 001fe)
>     ( R3: 001fe)  ( R7: 001fe)  (R11: 001fe)  (R15: 001fe)
>

**Comment by iddq** [comment]
(gpio access, so jtaglib is in use)

**Comment by dlbeer** [comment]
On Sat, May 30, 2020 at 07:59:17AM -0700, Gabor wrote:
> (gpio access, so jtaglib is in use)

Unfortunately I don't have suitable hardware to test this here. If you
want to experiment with the JTAG implementation, I'm happy to answer any
questions you might have.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by iddq** [comment]
can we debug it somehow? I don't find any doc about register reading.

**Comment by iddq** [comment]
I think the instruction is not executed. I modified 0x1fe to 0x200 and memory at address 0x200 is still unmodified.

**Comment by dlbeer** [comment]
On Sun, May 31, 2020 at 08:59:30PM -0700, Gabor wrote:
> can we debug it somehow? I don't find any doc about register reading.

I'm happy to answer questions, but unfortunately I don't have a lot of
time to dive in with debugging right now.

If you want to understand how the JTAG interface works, probably the
best thing to read first is the MSP430 Memory Programming User Guide.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B
